Repository saros-project/saros, pull requests merged in 2019-11, with the labels that each got.

#735 [BUILD][I] Update build IntelliJ version to 2019.2.4
  intellij/build.gradle
Labels: Area: Infrastructure, Area: IntelliJ

#733 [BUILD] Include grade sources when downloading gradelw
  gradle/wrapper/gradle-wrapper.properties
Labels: Area: Infrastructure

#739 Amend README
  README.md
Labels: Area: Documentation

#746 [BUILD][I] Fix Saros/I build script to allow import into Eclipse
  intellij/build.gradle
Labels: Area: IntelliJ, Type: Bug

#578 [DOC] Migrate research docs
  docs/_data/navigation.yml
  docs/assets/css/style.scss
  docs/research/index.md
Labels: Area: Documentation, Type: Feature

#749 [INTERNAL][I] Avoid usage of IResource methods using project paths
  intellij/src/saros/intellij/editor/LocalEditorManipulator.java
  intellij/src/saros/intellij/ui/views/buttons/ConsistencyButton.java
Labels: Area: IntelliJ, Aspect: User Experience

#753 Update saros-for-intellij link
  docs/documentation/faq.md
Labels: Area: Documentation

#756 [DOC] Correct CSS selector for gap between tab and content
  docs/assets/css/style.scss
Labels: Area: Documentation

#760 [DOC] Set title in head
  docs/_includes/head.html
Labels: Area: Documentation

#751 Update google java format info
  docs/contribute/development-environment.md
Labels: Area: Documentation

#759 [DOC][BUILD] Add information about Windows drive restrictions
  docs/contribute/development-environment.md
Labels: Area: Documentation

#763 [DOC] Remove server release link
  docs/documentation/saros-server.md
Labels: Area: Documentation

#757 [DOC] Change README logo position
  README.md
  docs/assets/images/logo/saros-logo.svg
Labels: Area: Documentation

#767 Use ConnectionHandler instead of XMPPConnectionService
  core/src/saros/communication/connection/ConnectionHandler.java
  core/src/saros/communication/connection/IConnectionStateListener.java
  core/src/saros/session/SarosSessionManager.java
  core/test/junit/saros/session/SarosSessionManagerTest.java
  eclipse/src/saros/ui/actions/DeleteContactAction.java
  eclipse/src/saros/ui/actions/NewContactAction.java
  eclipse/src/saros/ui/actions/OpenChatAction.java
  eclipse/src/saros/ui/actions/RenameContactAction.java
  eclipse/src/saros/ui/widgets/viewer/session/XMPPSessionDisplayComposite.java
  eclipse/src/saros/util/log/JIDFileAppender.java
  intellij/src/saros/intellij/ui/tree/SessionAndContactsTreeView.java
Labels: Area: Core, Area: Eclipse, Area: IntelliJ

#755 Remove eslint information from PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: Area: Documentation, Area: Infrastructure

#773 Update development setup guide
  docs/contribute/development-environment.md
Labels: Area: Documentation

#765 [BUILD] Execute stf tests on pr/stf/* branches
  .github/workflows/stf.yml
Labels: Area: Eclipse, Area: Infrastructure, Aspect: Test

#766 Remove old Discovery Manager From Eclipse
  core/META-INF/MANIFEST.MF
  core/src/saros/SarosConstants.java
  core/src/saros/communication/connection/ConnectionHandler.java
  core/src/saros/negotiation/OutgoingSessionNegotiation.java
  core/src/saros/net/ResourceFeature.java
  core/src/saros/net/xmpp/contact/DiscoveryService.java
  core/src/saros/net/xmpp/contact/IContactsUpdate.java
  core/src/saros/net/xmpp/contact/XMPPContact.java
  core/src/saros/net/xmpp/contact/XMPPContactsService.java
  eclipse/src/saros/ui/eventhandler/ServerPreferenceHandler.java
  eclipse/src/saros/ui/views/SarosView.java
  eclipse/src/saros/ui/wizards/pages/ContactSelectionWizardPage.java
  server/src/saros/server/net/ServerFeatureAdvertiser.java
Labels: Area: Core, Area: Eclipse

#778 [BUILD][I] Update default IntelliJ version for build to 2019.3
  intellij/build.gradle
Labels: Area: IntelliJ

#779 [E] Remove Simple Roster References
  eclipse/src/saros/ui/menuContributions/StartSessionWithProjects.java
  eclipse/src/saros/ui/model/roster/RosterCheckStateProvider.java
  eclipse/src/saros/ui/model/roster/RosterComparator.java
  eclipse/src/saros/ui/widgets/viewer/session/HideContactsInSessionFilter.java
  eclipse/src/saros/ui/wizards/pages/ContactSelectionWizardPage.java
Labels: Area: Eclipse

#777 Replace RosterListener in SarosView
  eclipse/src/saros/ui/views/SarosView.java
Labels: Area: Eclipse
