Repository saros-project/saros, pull requests merged in 2019-04, with the labels that each got.

#498 [BUILD][I] Add settings changes done automatically by Intellij
  .idea/gradle.xml
  .idea/misc.xml
Labels: build, intellij

#499 [FIX][I] #479 Correctly trigger an active negotiation cancel
  intellij/src/saros/intellij/ui/wizards/AddProjectToSessionWizard.java
Labels: bug, intellij

#502 [DOC] Reference old documentation
  docs/contribute/index.md
Labels: documentation

#465 [BUILD] Change to new semantic version 15.0.0
  eclipse/META-INF/MANIFEST.MF
  eclipse/feature/feature.xml
  server/src/saros/server/SarosServer.java
  ui.frontend/META-INF/MANIFEST.MF
  ui/META-INF/MANIFEST.MF
  whiteboard/META-INF/MANIFEST.MF
Labels: release

#501 [DOC] Add naming conventions
  docs/contribute/best-practices.md
  docs/contribute/guidelines.md
Labels: documentation
