Repository saros-project/saros, pull requests merged in 2020-07, with the labels that each got.

#1062 [BUILD] Enable manual triggering of the STF action
  .github/workflows/stf.yml
Labels: Area: Infrastructure

#1063 [BUILD] Use picocontainer jar
  .gitignore
  .idea/compiler.xml
  .idea/gradle.xml
  build.gradle.kts
  buildSrc/src/main/java/saros/gradle/eclipse/SarosEclipsePlugin.java
  buildSrc/src/main/java/saros/gradle/eclipse/configurator/EclipseConfigurator.java
  core/build.gradle.kts
  core/picocontainer/.settings/org.eclipse.jdt.core.prefs
  core/picocontainer/build.gradle.kts
  core/picocontainer/src/main/java/org/picocontainer/parameters/BasicComponentParameter.java
  core/picocontainer/src/main/java/org/picocontainer/parameters/annotation_resolve_fix.patch
  core/picocontainer/src/test/java/org/picocontainer/parameters/PicoAnnotationPatchTest.java
  eclipse/build.gradle.kts
  libs/picocontainer-2.11.2-patched_relocated.jar
  settings.gradle.kts
  stf.test/build.gradle.kts
  stf/build.gradle.kts
Labels: Area: Infrastructure

#1061 [INTERNAL][CORE] Pass JID of local user to session CTOR
  core/src/saros/session/SarosSessionManager.java
  core/src/saros/session/internal/SarosSession.java
  core/test/junit/saros/session/SarosSessionManagerTest.java
  eclipse/test/junit/saros/session/internal/SarosSessionTest.java
Labels: Area: Core

#1066 [STF] Ignore case during contact order check
  stf.test/test/saros/stf/test/roster/SortContactsOnlineOverOfflineTest.java
Labels: Area: Eclipse, Aspect: Test, Type: Bug

#1068 [DOC] Add info where to get a JDK8
  docs/contribute/development-environment.md
Labels: Area: Documentation, Area: Infrastructure

#1070 [DOC] Add eclipse version restriction to dev-env
  docs/contribute/development-environment.md
Labels: Area: Documentation, Area: Eclipse, Area: STF

#1075 [NOP] Rename master->coordinator, slave->worker
  docs/contribute/saros-testing-framework.md
  run_stf.sh
  travis/config/stf_config
  travis/script/stf/README.md
  travis/script/stf/coordinator/build_testee.sh
  travis/script/stf/coordinator/setup_stf_ws.sh
  travis/script/stf/coordinator/start_stf_self_tests.sh
  travis/script/stf/coordinator/start_stf_tests.sh
  travis/script/stf/coordinator_setup_utils.sh
  travis/script/stf/master_setup_utils.sh
  travis/script/stf/setup_stf_container.sh
  travis/script/stf/shared_vars.sh
  travis/script/stf/worker/start_eclipse.sh
  travis/script/stf/worker_setup_utils.sh
Labels: Area: Documentation, Area: Infrastructure, Area: STF
