Repository saros-project/saros, pull requests merged in 2020-06, with the labels that each got.

#1029 [INTERNAL] Remove feedback and statistics
  eclipse/plugin.xml
  eclipse/saros.properties
  eclipse/src/saros/EclipsePluginLifecycle.java
  eclipse/src/saros/StartupSaros.java
  eclipse/src/saros/feedback/AbstractFeedbackManager.java
  eclipse/src/saros/feedback/AbstractStatisticCollector.java
  eclipse/src/saros/feedback/DataTransferCollector.java
  eclipse/src/saros/feedback/ErrorLogManager.java
  eclipse/src/saros/feedback/FeedbackInterval.java
  eclipse/src/saros/feedback/FeedbackManager.java
  eclipse/src/saros/feedback/FeedbackPreferences.java
  eclipse/src/saros/feedback/FileSubmitter.java
  eclipse/src/saros/feedback/FollowModeCollector.java
  eclipse/src/saros/feedback/JumpFeatureUsageCollector.java
  eclipse/src/saros/feedback/Messages.java
  eclipse/src/saros/feedback/ParticipantCollector.java
  eclipse/src/saros/feedback/PermissionChangeCollector.java
  eclipse/src/saros/feedback/ProjectCollector.java
  eclipse/src/saros/feedback/SelectionCollector.java
  eclipse/src/saros/feedback/SessionDataCollector.java
  eclipse/src/saros/feedback/SessionStatistic.java
  eclipse/src/saros/feedback/StatisticManager.java
  eclipse/src/saros/feedback/StatisticManagerConfiguration.java
  eclipse/src/saros/feedback/TextEditCollector.java
  eclipse/src/saros/feedback/messages.properties
  eclipse/src/saros/feedback/package-info.java
  eclipse/src/saros/preferences/EclipsePreferenceInitializer.java
  eclipse/src/saros/project/internal/SarosEclipseSessionContextFactory.java
  eclipse/src/saros/ui/dialogs/FeedbackDialog.java
  eclipse/src/saros/ui/dialogs/package-info.java
  eclipse/src/saros/ui/preference_pages/FeedbackPreferencePage.java
  eclipse/src/saros/ui/wizards/ConfigurationWizard.java
  eclipse/src/saros/ui/wizards/pages/ConfigurationSettingsWizardPage.java
  eclipse/src/saros/ui/wizards/pages/ConfigurationSummaryWizardPage.java
  eclipse/test/junit/saros/SarosEclipseTestSuite.java
  eclipse/test/junit/saros/feedback/StatisticCollectorTest.java
  eclipse/test/junit/saros/feedback/TestSuite.java
  eclipse/test/junit/saros/session/internal/SarosSessionTest.java
  stf/src/saros/stf/client/StfTestCase.java
  stf/src/saros/stf/server/rmi/superbot/component/menubar/menu/submenu/ISarosPreferences.java
  stf/src/saros/stf/server/rmi/superbot/component/menubar/menu/submenu/impl/SarosPreferences.java
  stf/src/saros/stf/shared/Configuration.java
Labels: Area: Eclipse

#1031 [BUILD] Include grade sources when downloading gradlew
  gradle/wrapper/gradle-wrapper.properties
Labels: Area: Infrastructure

#1047 [BUILD] Workaround failing STF Tests
  travis/script/stf/master_setup_utils.sh
Labels: Area: Eclipse, Area: Infrastructure, Type: Bug
